# Generated by Django 4.2 on 2023-04-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=70)),
                ("min_bid", models.IntegerField(blank=True, null=True)),
                ("info", models.CharField(blank=True, max_length=200)),
                ("create_date", models.DateField()),
            ],
        ),
    ]
