# Generated by Django 4.2 on 2023-04-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0002_rename_goods_items"),
    ]

    operations = [
        migrations.RenameModel(old_name="items", new_name="item",),
    ]
