# Generated by Django 4.2 on 2023-04-22 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0004_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="phone",
            field=models.CharField(
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^([0-9]{3})-?([0-9]{3})-?([0-9]{4})$"
                    )
                ],
            ),
        ),
    ]
