# Generated by Django 4.2 on 2023-04-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0005_item_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
