# Generated by Django 4.2 on 2023-04-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auction_app", "0006_alter_item_create_date_alter_item_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="create_date", new_name="create_time",
        ),
    ]
